Adiciona Jusbrasil e Buser à seção de patrocinadoras
pythonbrasil/pybr2021-site pull request #25
Opened 2021-09-11 16:20 UTC by muriloviana

## Issues relacionadas

- closes #14 

## Descrição

A seção de patrocinadoras foi refeita para dispor as divisões de patrocínio e as empresas em seus respectivos planos. Utilizei o mesmo svg do site de 2019 para dividir os planos. O plano ouro ficou com dimensões 400x400 e o prata 300x300.

Caso queiram outro ícone nas divisões de planos, ou apenas um texto solto, ou mudar a cor dos planos, ou até mesmo mudar as dimensões dos logos das patrocinadoras, estou 100% aberto a sugestões 😉 

## Preview

![Screen Shot 2021-09-11 at 13 07 24](https://user-images.githubusercontent.com/6524275/132954297-a353c61f-b501-4551-b14e-25f1f64f15b5.png)

![Screen Shot 2021-09-11 at 13 08 01](https://user-images.githubusercontent.com/6524275/132954301-8ec6a439-e5ce-48d4-82d7-55dbc77193a0.png)

2021-09-13 20:42 UTC, muriloviana commented
Busquei algumas referências de eventos com fundo branco:

https://thedevconf.com/tdc/2021/patrocinadores?

![Screen Shot 2021-09-13 at 17 34 39](https://user-images.githubusercontent.com/6524275/133152940-d2dada84-cd45-4583-8621-b08d9848c7c2.png)

https://2021.djangocon.eu/sponsors/sponsors/

![Screen Shot 2021-09-13 at 17 35 38](https://user-images.githubusercontent.com/6524275/133152975-3c1691b8-7033-4140-b8e8-ef922d807a0c.png)

Minha única ressalva quanto a cores de fundo diferentes é parecer outra seção do site. Talvez uma cor bem próxima do fundo, para gerar um constraste bem de leve funcione. Outra opção é um linha separando os planos.

2021-09-13 20:48 UTC, cecivieira commented
Acho que esse traço entre as categorias já resolve. Além da descrição, poderíamos linkar para o site da patrocinadora. O que tu acha? Segue abaixo o link e descrição pra gente testar:

**Jusbrasil**: Somos uma empresa de tecnologia resolvendo velhos problemas com novas soluções. Conectando pessoas à justiça através de advogados e informação jurídica 
https://www.jusbrasil.com.br/home

**Buser**: A Buser é a startup que está revolucionando a forma de viajar de ônibus no Brasil. Mais do que só cidades, conectamos pessoas, histórias e famílias. Oferecemos uma experiência de qualidade para os nossos viajantes e estamos entrando em um novo mercado: o de encomendas. 
https://www.buser.com.br/

**Ebury**: Ebury é uma fintech, especialista em soluções financeiras, incluindo pagamentos internacionais e estratégias para redução de risco de câmbio. A empresa utiliza as mais novas tecnologias para melhorar e automatizar serviços financeiros, direcionados para pequenos e médios negócios.
https://br.ebury.com/

2021-09-13 20:48 UTC, cecivieira commented
![image](https://user-images.githubusercontent.com/30605862/133154252-0ba1048c-a0cd-4824-bae6-32c983c71ee7.png)

2021-09-13 20:57 UTC, muriloviana commented
Mass!!! Acho super válido, vou fazer isso hoje à noite.

Só uma dúvida, a Ebury é ouro ou prata?

2021-09-13 20:58 UTC, cecivieira commented
Prata

2021-09-13 22:47 UTC, alynnefs commented
A proporção da logo de patrocinadores ouro é 25% maior que a prata, que é 25% maior que a bronze

ouro - 100%
prata - 75%
bronze - 50%

2021-09-14 21:18 UTC, muriloviana commented
Adicionado os textos e a nova patrocinadora prata Ebury:

![Screen Shot 2021-09-14 at 18 16 18](https://user-images.githubusercontent.com/6524275/133335253-787da671-0505-428d-8ba8-ec2e6a918021.png)

P.S. A logo da buser ficou menor que a Ebury pois a imagem que foi disponibilizado tem uma "sobra" a mais, enquanto a da Ebury tá ajustada à logo.

2021-09-14 21:20 UTC, muriloviana commented
Outro detalhe, vocês preferem o texto justificado ou alinhado ao centro?

2021-09-14 21:22 UTC, gabubellon commented
Acho que o logo e texto da Ouro e Prata estão de tamanhos muito próximos, podemo aumentar o da ouro e/ou reduzir um poucp mais o da prata.

Acho importante que o destaque seja bem visivel

2021-09-14 21:22 UTC, gabubellon commented
> Outro detalhe, vocês preferem o texto justificado ou alinhado ao centro?

Gosto como o texto está, alinhado ao centro do logo

2021-09-14 21:37 UTC, muriloviana commented
@gabubellon a diferença de 25% entre as logos fica pouco mesmo devido ao tamanho delas. Pra ficar uma diferença muito grande as logos precisariam ficar com um tamanho ainda maior, daí acho que não fica legal na tela. Tem outro detalhe que acaba influenciando, é a altura de cada logo.

Atualmente o gold está com 300x300 e o prata 225x225.

2021-09-14 21:46 UTC, muriloviana commented
Define uma altura máxima de 60px para todas as logos, daí ficou melhor visualmente falando 😅 

Isso gera apenas uma ressalva, se tivermos uma logo com altura maior do que largura acabará ficando bem pequeno.

2021-09-14 22:12 UTC, alynnefs commented
@muriloviana dá muito trabalho descer o texto da buser pra ficar alinhado com o da ebury? na minha cabeça um <br> funciona, mas não cheguei a olhar o código :(

2021-09-15 03:00 UTC, muriloviana commented
@alynnefs depois de apanhar um pouco para o CSS acho que consegui 😅 

![Screen Shot 2021-09-15 at 00 00 13](https://user-images.githubusercontent.com/6524275/133363287-0a571073-e344-4f29-bcb9-71f8ed8ba0e0.png)

2021-09-15 11:46 UTC, gabubellon approved these changes

2021-09-16 14:56 UTC, alynnefs requested changes
desculpa, deu conflito depois do merge :(
eu até consigo editar, mas deixo qual versão?
@muriloviana @cecivieira

2021-09-16 15:03 UTC, alynnefs commented
@muriloviana boa! Eu li os comentários, mas não consegui "visualizar" exatamente onde que ia conflitar

2021-09-16 15:05 UTC, alynnefs approved these changes

2021-09-16 15:05 UTC, merged